import Vue from 'vue'
import { Tab, Tabs, Checkbox, Rate, Icon, Tabbar, TabbarItem, NavBar, Toast, Search, Swipe, SwipeItem, Lazyload, Grid, GridItem, Image, Sidebar, SidebarItem, Popup, ActionSheet, Dialog } from 'vant'
Vue.use(Checkbox)
Vue.use(Toast)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(NavBar)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Lazyload)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Image)
Vue.use(Icon)
Vue.use(Sidebar)
Vue.use(SidebarItem)
Vue.use(Popup)
Vue.use(ActionSheet)
Vue.use(Rate)
// 全局注册
Vue.use(Dialog)
Vue.use(Tabs)
Vue.use(Tab)
